global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'ai-chatbot'
    static_configs:
      - targets: ['ai-chatbot-service.ai-platform.svc.cluster.local:8000']
    metrics_path: '/metrics'
