name: AIOps Pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  monitor-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install prometheus_client

      - name: Run System Monitoring Script
        run: |
          python src/aiops/monitoring/system_monitor.py 