name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v1.31.1

    - name: Cache Deno modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json') }}
        restore-keys: |
          ${{ runner.os }}-deno-

    - name: Cache TensorFlow types
      uses: actions/cache@v3
      with:
        path: |
          ./src/types/
        key: ${{ runner.os }}-types-${{ hashFiles('**/src/types/*.d.ts') }}
        restore-keys: |
          ${{ runner.os }}-types-

    - name: Run Lint
      run: deno lint frontend/deno_app

    - name: Run Tests
      run: deno test --allow-net --allow-read --allow-env frontend/deno_app

    - name: Security Scans
      run: snyk test --severity-threshold=medium
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}