name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate Configurations
        run: |
          ./scripts/ci/validate_configs.sh
          ./scripts/ci/check_dependencies.sh

  test:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, rust, go, cpp]
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Tests
        run: ./scripts/ci/run_tests.sh ${{ matrix.language }}

  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Security Scan
        run: ./scripts/ci/security_scan.sh

  deploy:
    needs: [test, security]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: ./scripts/deployment/deploy.sh

