name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate Configurations
        run: |
          ./scripts/ci/validate_configs.sh || handle_error ${LINENO} "Configuration Validation Failed."
          ./scripts/ci/check_dependencies.sh || handle_error ${LINENO} "Dependency Check Failed."

  test:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, rust, go, cpp]
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Tests for ${{ matrix.language }}
        run: ./scripts/ci/run_tests.sh ${{ matrix.language }} || handle_error ${LINENO} "Tests failed for ${matrix.language}."

  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Security Scan
        run: ./scripts/ci/security_scan.sh || handle_error ${LINENO} "Security Scan Failed."

  deploy:
    needs: [test, security]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy
        run: ./scripts/deployment/deploy.sh || handle_error ${LINENO} "Deployment Failed."