name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/python_service/requirements.txt

      - name: Run Linters and Tests
        run: |
          black --check src tests
          flake8 src tests
          mypy src
          python -m unittest discover -s tests/unit
          python -m unittest discover -s tests/integration
          python -m unittest discover -s tests/e2e

      - name: Build Docker Images
        run: |
          docker build -t yourusername/ai_chatbot:latest -f deployment/docker/ai_chatbot.Dockerfile .
          docker build -t yourusername/healthcare_ai:latest -f deployment/docker/healthcare_ai.Dockerfile .

      - name: Push Docker Images
        run: |
          docker push yourusername/ai_chatbot:latest
          docker push yourusername/healthcare_ai:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name your-cluster-name
          kubectl apply -f deployment/k8s/

      - name: Run Security Scans
        run: |
          npm audit --audit-level=moderate
          cargo audit
          snyk test --severity-threshold=medium
          snyk monitor --org=${{ secrets.SNYK_ORG_ID }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor Deployment
        run: |
          attempts=0
          until aws ecs describe-services --cluster your-cluster --services your-service --query 'services[0].status' | grep "ACTIVE"
          do
            if [ $attempts -eq 5 ]; then
              echo "Deployment health check failed"
              exit 1
            fi
            attempts=$((attempts+1))
            sleep 30
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Generate Deployment Report
        run: |
          {
            echo "## Deployment Report - $(date)"
            echo "### Status Overview"
            echo "- Environment: Production"
            echo "- Commit: ${{ github.sha }}"
            echo "### Health Checks"
            echo "- Security Scans: ✅"
            echo "- Deployment Status: ✅"
          } > deployment-report.md

      - name: Upload Deployment Report
        uses: actions/upload-artifact@v2
        with:
          name: deployment-report
          path: deployment-report.md

      - name: Send Deployment Notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment report generated and uploaded."}' ${{ secrets.SLACK_WEBHOOK_URL }}